import logger from '../config/logger.js';
import dotenv from 'dotenv';
import fetch from 'node-fetch';
import jwt from 'jsonwebtoken';

// Ensure environment variables are loaded
dotenv.config();

// Chatwoot API base URL
const CHATWOOT_API_BASE =
  process.env.CHATWOOT_API_BASE || 'http://localhost:3000';

// JWT Secret for token validation
const JWT_SECRET =
  process.env.CHATWOOT_JWT_SECRET ||
  process.env.RAILS_SECRET_KEY_BASE ||
  process.env.JWT_SECRET;

if (!JWT_SECRET) {
  logger.error('JWT secret not configured. Set CHATWOOT_JWT_SECRET or RAILS_SECRET_KEY_BASE environment variable.');
}

/**
 * Middleware to authenticate Chatwoot JWT tokens
 * Validates tokens generated by Chatwoot's FlowEditor token endpoint
 */
export const authenticateChatwootToken = async (req, res, next) => {
  // Development mode bypass - allow requests without authentication
  if (
    process.env.NODE_ENV === 'development' ||
    process.env.BYPASS_AUTH === 'true'
  ) {
    logger.info('Development mode: Bypassing authentication', {
      ip: req.ip,
      url: req.url,
    });

    // Set a mock user context for development
    req.user = {
      id: 1,
      account_id: 1, // Default account ID for development
      email: 'dev@floweditor.com',
      role: 'administrator',
      uid: 'dev-user',
      client: 'dev-client',
      tokenData: {
        user_id: 1,
        account_id: 1,
        email: 'dev@floweditor.com',
      },
    };

    return next();
  }

  // Extract token from Authorization header or query parameter
  const authHeader = req.headers['authorization'];
  const token = authHeader && authHeader.split(' ')[1]; // Bearer TOKEN
  const queryToken = req.query.token;
  
  const jwtToken = token || queryToken;

  if (!jwtToken) {
    logger.warn('Chatwoot authentication failed: No token provided', {
      ip: req.ip,
      url: req.url,
      userAgent: req.get('User-Agent'),
    });
    return res.status(401).json({
      error: 'Access token required for Chatwoot integration',
      code: 'CHATWOOT_TOKEN_REQUIRED',
    });
  }

  if (!JWT_SECRET) {
    logger.error('Chatwoot authentication failed: JWT secret not configured');
    return res.status(500).json({
      error: 'Server configuration error',
      code: 'JWT_SECRET_MISSING',
    });
  }

  try {
    // Verify and decode the JWT token
    const decoded = jwt.verify(jwtToken, JWT_SECRET);

    // Validate required token fields
    if (!decoded.account_id || !decoded.user_id) {
      logger.warn('Chatwoot authentication failed: Invalid token payload', {
        payload: decoded,
        ip: req.ip,
      });
      return res.status(403).json({
        error: 'Invalid token payload',
        code: 'CHATWOOT_TOKEN_PAYLOAD_INVALID',
      });
    }

    // Check token expiration
    if (decoded.exp && Date.now() >= decoded.exp * 1000) {
      logger.warn('Chatwoot authentication failed: Token expired', {
        exp: decoded.exp,
        now: Date.now() / 1000,
        ip: req.ip,
      });
      return res.status(403).json({
        error: 'Token expired',
        code: 'CHATWOOT_TOKEN_EXPIRED',
      });
    }

    // Set user context from token
    req.user = {
      id: decoded.user_id,
      account_id: decoded.account_id,
      email: decoded.user_email || decoded.email,
      role: decoded.role || 'user',
      tokenData: decoded,
    };

    // Store account ID for later use
    req.account_id = req.user.account_id;

    logger.info('Chatwoot user authenticated successfully', {
      user_id: req.user.id,
      account_id: req.user.account_id,
      email: req.user.email,
      ip: req.ip,
    });

    return next();

  } catch (error) {
    logger.warn('Chatwoot authentication failed: Invalid token', {
      error: error.message,
      ip: req.ip,
      userAgent: req.get('User-Agent'),
    });
    return res.status(403).json({
      error: 'Invalid or expired token',
      code: 'CHATWOOT_TOKEN_INVALID',
    });
  }
};

/**
 * Middleware to ensure user can only access their account's data
 * Must be used after authenticateChatwootToken
 */
export const requireChatwootAccountAccess = (req, res, next) => {
  // Development mode bypass - allow all account access
  if (
    process.env.NODE_ENV === 'development' ||
    process.env.BYPASS_AUTH === 'true'
  ) {
    logger.info('Development mode: Bypassing account access check', {
      requested_account: req.account_id || req.headers['x-account-id'],
      user_account: req.user?.account_id,
      ip: req.ip,
      url: req.url,
      params: req.params,
    });

    // Ensure req.account_id is set in development mode
    // Check multiple sources for account ID
    const accountId = 
      req.account_id ||
      req.accountId ||
      req.params.accountId ||
      req.headers['x-account-id'] ||
      req.query.account_id ||
      1;

    req.account_id = parseInt(accountId);
    req.accountId = req.account_id; // Ensure both formats are available

    logger.info('Development mode: Account ID set', {
      account_id: req.account_id,
      accountId: req.accountId,
      source: req.account_id ? 'existing' : req.accountId ? 'accountId' : req.params.accountId ? 'params' : req.headers['x-account-id'] ? 'headers' : req.query.account_id ? 'query' : 'default',
    });

    return next();
  }

  // Get account ID from URL params, headers, or query params
  const requestedAccountId =
    req.account_id ||
    req.accountId ||
    req.params.accountId ||
    req.headers['x-account-id'] ||
    req.query.account_id;

  if (!requestedAccountId) {
    logger.warn('Chatwoot account access denied: No account ID provided', {
      user_id: req.user?.id,
      user_account: req.user?.account_id,
      ip: req.ip,
      url: req.url,
      params: req.params,
    });
    return res.status(400).json({
      success: false,
      error: 'Account ID required',
      code: 'ACCOUNT_ID_REQUIRED',
    });
  }

  // Verify user has access to the requested account
  const userAccountId = req.user?.account_id;

  if (
    !userAccountId ||
    userAccountId.toString() !== requestedAccountId.toString()
  ) {
    logger.warn(
      'Chatwoot account access denied: User does not have access to requested account',
      {
        user_id: req.user?.id,
        user_account: userAccountId,
        requested_account: requestedAccountId,
        ip: req.ip,
        url: req.url,
      },
    );
    return res.status(403).json({
      error: 'Access denied to requested account',
      code: 'CHATWOOT_ACCOUNT_ACCESS_DENIED',
    });
  }

  logger.info('Chatwoot account access granted', {
    user_id: req.user.id,
    account_id: requestedAccountId,
    ip: req.ip,
  });

  next();
};
